// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto14.models;

namespace Proyecto14.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20200306065028_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyecto14.models.categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategoria");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Proyecto14.models.categoriaSubcategoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SubCategoriaidSubCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("categoriaidCategoria")
                        .HasColumnType("int");

                    b.Property<int>("idCategoria")
                        .HasColumnType("int");

                    b.Property<int>("idSubCategoria")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SubCategoriaidSubCategoria");

                    b.HasIndex("categoriaidCategoria");

                    b.ToTable("CategoriaSubCategorias");
                });

            modelBuilder.Entity("Proyecto14.models.subCategoria", b =>
                {
                    b.Property<int>("idSubCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSubCategoria");

                    b.ToTable("subCategorias");
                });

            modelBuilder.Entity("Proyecto14.models.categoriaSubcategoria", b =>
                {
                    b.HasOne("Proyecto14.models.subCategoria", "SubCategoria")
                        .WithMany("categoriaSubCategorias")
                        .HasForeignKey("SubCategoriaidSubCategoria");

                    b.HasOne("Proyecto14.models.categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaidCategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
